name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore SourceCode/ETDValidator/ETDValidator.sln
      - name: Build
        run: dotnet build SourceCode/ETDValidator/ETDValidator.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test SourceCode/ETDValidator/ETDValidator.sln --no-restore --verbosity normal
      - name: Upload dotnet build results
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-results
          path: SourceCode/ETDValidator/ETDValidator/bin/
